name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-scan-push:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build image
      run: docker build -t 10.6.0.190:80/local/website-jacky:${{ github.sha }} .
      with:
        file: ./_work/test-vlaujacky/test-vlaujacky/app_python/Dockerfile
        
    - name: Scan with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 10.6.0.190:80/local/website-jacky:${{ github.sha }}
        exit-code: '1'
        severity: 'CRITICAL,HIGH'

    - name: Push image
      run: docker push 10.6.0.190:80/local/website-jacky:${{ github.sha }}
